BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Dobavljac" (
	"IDDobavljaca"	INTEGER,
	"Iime"	TEXT,
	"Adresa"	TEXT,
	"e-mail"	TEXT,
	"Ugovor"	REAL,
	PRIMARY KEY("IDDobavljaca")
);
CREATE TABLE IF NOT EXISTS "Jemstvo" (
	"ID"	INTEGER,
	"Ugovor"	REAL,
	"PravnoLice"	TEXT,
	"Uslovi"	TEXT,
	PRIMARY KEY("ID")
);
CREATE TABLE IF NOT EXISTS "Kupci" (
	"IDKupca"	INTEGER,
	"ImeKupca"	TEXT,
	"Ugovor"	REAL,
	"Adresa"	TEXT,
	PRIMARY KEY("IDKupca")
);
CREATE TABLE IF NOT EXISTS "PravnoLice" (
	"IDPravnogLica"	INTEGER,
	"Ime"	TEXT,
	"Kontakt"	TEXT,
	"e-mail"	TEXT,
	PRIMARY KEY("IDPravnogLica")
);
CREATE TABLE IF NOT EXISTS "Ugovor" (
	"IDUgovora"	INTEGER,
	"DatumFormiranjaUgovora"	TEXT,
	"PravnoLice"	TEXT,
	PRIMARY KEY("IDUgovora")
);
CREATE TABLE IF NOT EXISTS "Zaposleni" (
	"IDZaposenih"	INTEGER,
	"ImeZaposlenog"	TEXT,
	"Ugovor"	REAL,
	"Adresa"	TEXT,
	PRIMARY KEY("IDZaposenih")
);
INSERT INTO "Dobavljac" VALUES (2,'Mika','Beogradska 123','mika@gmail.com','DA');
INSERT INTO "Dobavljac" VALUES (3,'Pera','Celjska 2','pera@gmail.com','DA');
INSERT INTO "Dobavljac" VALUES (4,'Laza','Beogradska 44','laza@gmail.com','NE');
INSERT INTO "Dobavljac" VALUES (5,'Paja','Aleksandra I 21','paja@gmail.com','DA');
INSERT INTO "Dobavljac" VALUES (6,'Mare','Pavla Vujisica 12','mare@gmail.com','NE');
INSERT INTO "Dobavljac" VALUES (7,'Kole','Beogradska 45','kole@gmail.com','NE');
INSERT INTO "Dobavljac" VALUES (8,'Ogi','Beogradska 55','ogi@gmail.com','NE');
INSERT INTO "Dobavljac" VALUES (9,'Laki','Aleksandra I 67','laki@gmail.com','DA');
INSERT INTO "Dobavljac" VALUES (10,'Mina','Celjska 22','mina@gmail.com','DA');
INSERT INTO "Dobavljac" VALUES (11,'Jana','Aleksandra I 111','jana@gmail.com','DA');
INSERT INTO "Dobavljac" VALUES (12,'Tina','Celjska 122','tina@gmail.com','DA');
INSERT INTO "Dobavljac" VALUES (13,'Mica','Pavla Vujisica 6','mica@gmail.com','DA');
INSERT INTO "Dobavljac" VALUES (14,'Joca','Aleksandra I 201','joca@gmail.com','NE');
INSERT INTO "Dobavljac" VALUES (15,'Nemanja','Beogradska 76','nemanja@gmail.com','NE');
INSERT INTO "Dobavljac" VALUES (16,'Neca','Pavla Vujisica 122','neca@gmail.com','NE');
INSERT INTO "Dobavljac" VALUES (17,'Jovan','Celjska 89','jovan@gmail.com','DA');
INSERT INTO "Dobavljac" VALUES (18,'Goran','Aleksandra I 40','goran@gmail.com','DA');
INSERT INTO "Dobavljac" VALUES (19,'Zoran','Beogradska 321','zoran@gmail.com','DA');
INSERT INTO "Dobavljac" VALUES (20,'Mateja','Pavla Vujisica 87','mateja@gmail.com','NE');
INSERT INTO "Dobavljac" VALUES (21,'Miki','Celjska 90','miki@gmail.com','DA');
INSERT INTO "Jemstvo" VALUES (1,'',NULL,NULL);
INSERT INTO "Jemstvo" VALUES (2,'',NULL,NULL);
INSERT INTO "Jemstvo" VALUES (3,'',NULL,NULL);
INSERT INTO "Jemstvo" VALUES (4,'',NULL,NULL);
INSERT INTO "Jemstvo" VALUES (5,'',NULL,NULL);
INSERT INTO "Jemstvo" VALUES (6,'',NULL,NULL);
INSERT INTO "Jemstvo" VALUES (7,'',NULL,NULL);
INSERT INTO "Jemstvo" VALUES (8,'',NULL,NULL);
INSERT INTO "Jemstvo" VALUES (9,'',NULL,NULL);
INSERT INTO "Jemstvo" VALUES (10,'',NULL,NULL);
INSERT INTO "Jemstvo" VALUES (11,'',NULL,NULL);
INSERT INTO "Jemstvo" VALUES (12,'',NULL,NULL);
INSERT INTO "Jemstvo" VALUES (13,'',NULL,NULL);
INSERT INTO "Jemstvo" VALUES (14,'',NULL,NULL);
INSERT INTO "Jemstvo" VALUES (15,'',NULL,NULL);
INSERT INTO "Jemstvo" VALUES (16,'',NULL,NULL);
INSERT INTO "Jemstvo" VALUES (17,'',NULL,NULL);
INSERT INTO "Jemstvo" VALUES (18,'',NULL,NULL);
INSERT INTO "Jemstvo" VALUES (19,NULL,NULL,NULL);
INSERT INTO "Jemstvo" VALUES (20,NULL,NULL,NULL);
INSERT INTO "Kupci" VALUES (1,NULL,NULL,NULL);
INSERT INTO "Kupci" VALUES (2,NULL,NULL,NULL);
INSERT INTO "Kupci" VALUES (3,NULL,NULL,NULL);
INSERT INTO "Kupci" VALUES (4,NULL,NULL,NULL);
INSERT INTO "Kupci" VALUES (5,NULL,NULL,NULL);
INSERT INTO "Kupci" VALUES (6,NULL,NULL,NULL);
INSERT INTO "Kupci" VALUES (7,NULL,NULL,NULL);
INSERT INTO "Kupci" VALUES (8,NULL,NULL,NULL);
INSERT INTO "Kupci" VALUES (9,NULL,NULL,NULL);
INSERT INTO "Kupci" VALUES (10,NULL,NULL,NULL);
INSERT INTO "Kupci" VALUES (11,NULL,NULL,NULL);
INSERT INTO "Kupci" VALUES (12,NULL,NULL,NULL);
INSERT INTO "Kupci" VALUES (13,NULL,NULL,NULL);
INSERT INTO "Kupci" VALUES (14,NULL,NULL,NULL);
INSERT INTO "Kupci" VALUES (15,NULL,NULL,NULL);
INSERT INTO "Kupci" VALUES (16,NULL,NULL,NULL);
INSERT INTO "Kupci" VALUES (17,NULL,NULL,NULL);
INSERT INTO "Kupci" VALUES (18,NULL,NULL,NULL);
INSERT INTO "Kupci" VALUES (19,NULL,NULL,NULL);
INSERT INTO "Kupci" VALUES (20,NULL,NULL,NULL);
INSERT INTO "PravnoLice" VALUES (1,NULL,NULL,NULL);
INSERT INTO "PravnoLice" VALUES (2,NULL,NULL,NULL);
INSERT INTO "PravnoLice" VALUES (3,NULL,NULL,NULL);
INSERT INTO "PravnoLice" VALUES (4,NULL,NULL,NULL);
INSERT INTO "PravnoLice" VALUES (5,NULL,NULL,NULL);
INSERT INTO "PravnoLice" VALUES (6,NULL,NULL,NULL);
INSERT INTO "PravnoLice" VALUES (7,NULL,NULL,NULL);
INSERT INTO "PravnoLice" VALUES (8,NULL,NULL,NULL);
INSERT INTO "PravnoLice" VALUES (9,NULL,NULL,NULL);
INSERT INTO "PravnoLice" VALUES (10,NULL,NULL,NULL);
INSERT INTO "PravnoLice" VALUES (11,NULL,NULL,NULL);
INSERT INTO "PravnoLice" VALUES (12,NULL,NULL,NULL);
INSERT INTO "PravnoLice" VALUES (13,NULL,NULL,NULL);
INSERT INTO "PravnoLice" VALUES (14,NULL,NULL,NULL);
INSERT INTO "PravnoLice" VALUES (15,NULL,NULL,NULL);
INSERT INTO "PravnoLice" VALUES (16,NULL,NULL,NULL);
INSERT INTO "PravnoLice" VALUES (17,NULL,NULL,NULL);
INSERT INTO "PravnoLice" VALUES (18,NULL,NULL,NULL);
INSERT INTO "PravnoLice" VALUES (19,NULL,NULL,NULL);
INSERT INTO "PravnoLice" VALUES (20,NULL,NULL,NULL);
INSERT INTO "Ugovor" VALUES (1,NULL,NULL);
INSERT INTO "Ugovor" VALUES (2,NULL,NULL);
INSERT INTO "Ugovor" VALUES (3,NULL,NULL);
INSERT INTO "Ugovor" VALUES (4,NULL,NULL);
INSERT INTO "Ugovor" VALUES (5,NULL,NULL);
INSERT INTO "Ugovor" VALUES (6,NULL,NULL);
INSERT INTO "Ugovor" VALUES (7,NULL,NULL);
INSERT INTO "Ugovor" VALUES (8,NULL,NULL);
INSERT INTO "Ugovor" VALUES (9,NULL,NULL);
INSERT INTO "Ugovor" VALUES (10,NULL,NULL);
INSERT INTO "Ugovor" VALUES (11,NULL,NULL);
INSERT INTO "Ugovor" VALUES (12,NULL,NULL);
INSERT INTO "Ugovor" VALUES (13,NULL,NULL);
INSERT INTO "Ugovor" VALUES (14,NULL,NULL);
INSERT INTO "Ugovor" VALUES (15,NULL,NULL);
INSERT INTO "Ugovor" VALUES (16,NULL,NULL);
INSERT INTO "Ugovor" VALUES (17,NULL,NULL);
INSERT INTO "Ugovor" VALUES (18,NULL,NULL);
INSERT INTO "Ugovor" VALUES (19,NULL,NULL);
INSERT INTO "Ugovor" VALUES (20,NULL,NULL);
INSERT INTO "Zaposleni" VALUES (1,NULL,NULL,NULL);
INSERT INTO "Zaposleni" VALUES (2,NULL,NULL,NULL);
INSERT INTO "Zaposleni" VALUES (3,NULL,NULL,NULL);
INSERT INTO "Zaposleni" VALUES (4,NULL,NULL,NULL);
INSERT INTO "Zaposleni" VALUES (5,NULL,NULL,NULL);
INSERT INTO "Zaposleni" VALUES (6,NULL,NULL,NULL);
INSERT INTO "Zaposleni" VALUES (7,NULL,NULL,NULL);
INSERT INTO "Zaposleni" VALUES (8,NULL,NULL,NULL);
INSERT INTO "Zaposleni" VALUES (9,NULL,NULL,NULL);
INSERT INTO "Zaposleni" VALUES (10,NULL,NULL,NULL);
INSERT INTO "Zaposleni" VALUES (11,NULL,NULL,NULL);
INSERT INTO "Zaposleni" VALUES (12,NULL,NULL,NULL);
INSERT INTO "Zaposleni" VALUES (13,NULL,NULL,NULL);
INSERT INTO "Zaposleni" VALUES (14,NULL,NULL,NULL);
INSERT INTO "Zaposleni" VALUES (15,NULL,NULL,NULL);
INSERT INTO "Zaposleni" VALUES (16,NULL,NULL,NULL);
INSERT INTO "Zaposleni" VALUES (17,NULL,NULL,NULL);
INSERT INTO "Zaposleni" VALUES (18,NULL,NULL,NULL);
INSERT INTO "Zaposleni" VALUES (19,NULL,NULL,NULL);
INSERT INTO "Zaposleni" VALUES (20,NULL,NULL,NULL);
COMMIT;
